### ISSUE TITLE
Feature request: create a Nuget package

### ISSUE THREAD

**Issue by jamiehowarth0** [JonasESmith/ZendeskSellApiClient#2]
Currently to be able to use this project, one must clone & compile yourself. Ideally this package would support releases via Nuget. Happy to devote some of my Azure Devops resources to enable this.

**Comment by JonasESmith** [comment]
That would be great, I haven't worked on this in quite a while so feel free
to do with it as you need!

**Comment by jamiehowarth0** [comment]
@JonasESmith I've just pushed a big refactor which cleans up the default behaviours quite nicely, including interface abstraction for method signatures, reusable RestClient with default headers, Nuget package options, and a (currently empty) NUnit test project. Do check it out & let me know what you think.

**Comment by jamiehowarth0** [comment]
This can now be closed.
